### ISSUE TITLE
API Reference - `pad_by_time`

### ISSUE THREAD

**Issue by JustinKurland** [business-science/pytimetk#137]
At the bottom of the API for `pad_by_time` in the "Pad with end dates specified" section the documentation is incomplete. Example needs to be fleshed out. 
<img width="874" alt="Screen Shot 2023-10-19 at 9 44 36 AM" src="https://github.com/business-science/pytimetk/assets/65054169/2f2df3b0-c602-4176-ac31-af8b4ca41646">

**Comment by JustinKurland** [comment]
Related to the API for `pad_by_time` I think that there is a mistake in the code for the `assign` this should be 'symbol' not 'id' as this has the unintended consequence of adding an additional 'id' column rather than simply forward filling the group column label of interest.

<img width="874" alt="Screen Shot 2023-10-19 at 10 20 34 AM" src="https://github.com/business-science/pytimetk/assets/65054169/c3aa1f35-cc38-43a3-9968-55b0785ac435">

**Comment by JustinKurland** [comment]
The documentation just simply need to be updated now. As I corrected the function to resolve this altogether. There is no need to use `.assign(symbol = lambda x: x['symbol'].ffill())` as the correct column is inferred automatically from the underlying dataframe. However the documentation needs to be updated accordingly.

**Comment by mdancho84** [comment]
Thanks for the help. Nice work! 😀
