### ISSUE TITLE
Pytimetk's Pandas requirement incompatible with Pycaret's Pandas requirement

### ISSUE THREAD

**Issue by nauscj** [business-science/pytimetk#141]
pycaret 3.1.0 depends on pandas<2.0.0 and >=1.3.0
pytimetk 0.1.0 depends on pandas<3.0.0 and >=2.1.0

**Comment by mdancho84** [comment]
I just relaxed the dependency to pandas 1.5.0. See if that works.

**Comment by mdancho84** [comment]
This should be fixed now.
