### ISSUE TITLE
How to Handle Dependencies: Balance Ease of Installation and Making Sure Our Package Works

### ISSUE THREAD

**Issue by mdancho84** [business-science/pytimetk#160]
We got our 1st GH Issue on a conflict between Pycaret and Pytimetk (https://github.com/business-science/pytimetk/issues/141). Because pycaret depends on sktime, which in turn requires pandas <2.0.0, pytimetk was not able to be installed in the same environment.

So this brings up an issue, I've addressed in the latest poetry dependencies. I've modified from pandas = "^2.1.1" to pandas = ">=1.5.0". This is where things get tricky.

Pandas 2.0.0 introduced breaking changes. One that has tripped me up is that pandas 1.5.0 did not always use group_keys by default. Pandas 2.0.0 did, so I designed everything assuming group_keys would be present in the return data frame's row index. Well, that's apparently not how pandas used to work. And now when I'm trying tk.anomalize() and tk.ts_summary() I found that my code broke. (Don't worry, I've already implemented the fix)

## What's My Point?

We need to balance flexibility so users can install pytimetk with how we test in github actions.

### I need your help:

1. First, let me know your thoughts, and if you've battled stuff like this before.
2. Second, we need to discuss how to modify the poetry dependencies to balance this.

Modifying the Dependencies:

1. First, the caret ^ can get us tripped up. pandas = "^1.5.0" won't allow pandas = ">=2.0.0". So I suggest we switch to >=

2. Second, I suggest we test with multiple versions of pandas and polars. Our package is heavily dependent on these "engines" - I've added a new pandas-checks.yaml to Github Actions which tests 1.5.0, 2.0.0, and the latest version.
![image](https://github.com/business-science/pytimetk/assets/13734662/672d9d9b-30ac-4a96-bd06-c047e7730ba5)

3. Third, we should also consider testing with matplotlib, plotly and plotnine since the plotting utilities are heavily dependent on these.

## Current Poetry Dependencies (2023-10-21)

```
[tool.poetry.dependencies]
python = ">=3.9"
pandas = ">=1.5.0"
pandas-flavor = "^0.6.0"
matplotlib = "^3.8.0"
plotnine = "^0.12.3"
plotly = "^5.17.0"
holidays = "^0.33"
tsfeatures = "^0.4.5"
statsmodels = "^0.14.0"
tqdm = "^4.66.1"
polars = "^0.19.8"
pyarrow = "^13.0.0"
pathos = "^0.3.1"
```

Thanks, Matt

**Comment by BrianMikinski** [comment]
Hey guys, thanks for all the hard work you've done. This seems like an awesome package.

I am running into an install issue right now when running either the standard pip install or the development build. The error message is "Getting requirements to build wheel ... error".

 I am running Python 3.12 and doing a standard pandas install with pip. If this belongs in a different issue I'm happy to break it out. Here's a screenshot of the error -

<img width="1283" alt="image" src="https://github.com/business-science/pytimetk/assets/2699324/2828fe1b-f24c-46ba-a5c3-a828c216d672">

Thanks and good luck!

**Comment by mdancho84** [comment]
@BrianMikinski if this is still an issue, please break out.
