### ISSUE TITLE
`tk.augment_fourier()`

### ISSUE THREAD

**Issue by mdancho84** [business-science/pytimetk#22]
Implement `tk.augment_fourier()` similar to how R timetk `tk_augment_fourier()` and `vec_fourier` work:

- date_to_seq_scale_factor: https://github.com/business-science/timetk/blob/b902278c4a7596846594502b4a21595f5018c84d/R/vec-fourier.R#L182
- calc_fourier: https://github.com/business-science/timetk/blob/b902278c4a7596846594502b4a21595f5018c84d/R/vec-fourier.R#L166
- fourier_vec: https://github.com/business-science/timetk/blob/b902278c4a7596846594502b4a21595f5018c84d/R/vec-fourier.R#L134
- augment_fourier: https://github.com/business-science/timetk/blob/b902278c4a7596846594502b4a21595f5018c84d/R/augment-tk_augment_fourier.R#L89

Lead: Justin Kurland

#2

**Comment by GTimothee** [comment]
I can try to help on this one :)

**Comment by mdancho84** [comment]
That would be great. The challenge is to get the peaks of the sin/cos to match the period or periods given. I want the functionality to be very similar to R timetk augment_fourier which depends on fourier_vec.

**Comment by JustinKurland** [comment]
Happy for @GTimothee to give this a go as I have been tackling other tasks presently.

**Comment by GTimothee** [comment]
OK I will do my best, let's start with this one :) I contacted JustinKurland privately and he kindly offered his help :)

**Comment by mdancho84** [comment]
Sounds great!!

**Comment by GTimothee** [comment]
Just to let you know I think I found a bug in the original implementatio. I found that this line https://github.com/business-science/pytimetk/blob/8b5014bfda7847d6a578e8e7e2bcac7e4c4a8fd9/src/pytimetk/core/fourier.py#L79 should be before data.copy() or it will break here: https://github.com/business-science/pytimetk/blob/8b5014bfda7847d6a578e8e7e2bcac7e4c4a8fd9/src/pytimetk/core/fourier.py#L86

Should I push a fix in a separate issue or should we ignore it and just wait for the new version of the function ?

**Comment by mdancho84** [comment]
Just push the fix, and we will get it updated. This way if we modify the original function, then the corrected version has the fix already in there.

**Comment by mdancho84** [comment]
@GTimothee Just a heads up - I've refactored this and the rest of the feature engineering functions to a new submodule called `feature_engineering`. Please do a git pull.

**Comment by GTimothee** [comment]
Sorry I did not see your message ! Will do

**Comment by mdancho84** [comment]
Done: Here are the docs: https://business-science.github.io/pytimetk/reference/augment_fourier.html#pytimetk.augment_fourier
