### ISSUE TITLE
Guide: Data Wrangling

### ISSUE THREAD

**Issue by mdancho84** [business-science/pytimetk#25]
Add guide on Data Wrangling. Cover functions with examples:

- [x] summarize_by_time()
- [x] future_frame()
- [x] pad_by_time()

Will be housed here: https://business-science.github.io/pytimetk/guides/04_wrangling.html

Lead: Lucas O

**Comment by LucasO21** [comment]
Hi @mdancho84, I'm not sure if there is an issue with `pad_by_time()` or maybe I'm not using it correctly. It appears the 'auto' option of the 'freq' parameter is ONLY detecting daily frequency.  When I try setting `freq` to `auto` for data with weekly or monthly frequency, I get an error saying `ValueError: The frequency could not be detectied.`

Here is the code I'm using to test daily pad by time - 

```
# Daily Example ----

date_range = pd.date_range(start = '2023-09-18', end = '2023-09-25')
value = range(len(date_range))

daily_df = pd.DataFrame({
	'date': date_range,
	'value': value
}) \
    .drop([5, 6])
    
daily_df \
	.pad_by_time(
		date_column = 'date',
		freq        = 'auto',
		
	)
```

And here is the code for weekly pad by time which errors - 

```
# Weekly Example ----

# Create a date range for 7 weeks
date_range = pd.date_range(start= "2023-01-01", periods=7, freq='W-SUN')
value = range(len(date_range))

weekly_df = pd.DataFrame({
	'week': date_range,
	'value': value
}) \
    .drop([2, 4])
    
weekly_df \
    .pad_by_time(
		date_column = 'week',
		freq        = 'auto'
	)

```

**Comment by mdancho84** [comment]
I'm going to remove the "auto" option. So just pretend it doesn't exist. And have the user specify the frequency to pad to.

**Comment by LucasO21** [comment]
Ok. Created a PR for `pad_by_time()` guides. I can get started on augment this weekend.

**Comment by mdancho84** [comment]
Thanks a lot. I'll fix pad by time soon.

**Comment by mdancho84** [comment]
#29 fixes this. Closing this issue.
