### ISSUE TITLE
Tests: Augment Functions

### ISSUE THREAD

**Issue by mdancho84** [business-science/pytimetk#27]
Need `pytest` tests for augment functions. (Use chatgpt to help)

- [ ] augment_timeseries_signature
- [ ] augment_holiday_signature 
- [ ] augment_lags 
- [ ] augment_leads 
- [ ] augment_rolling

 

#2

**Comment by tackes** [comment]
All tests in this issue have been completed.

- [x ]  augment_timeseries_signature
- [x]  augment_holiday_signature
- [x ]  augment_lags
- [x]  augment_leads
- [x]  augment_rolling

**Comment by tackes** [comment]
All tasks complete
