### ISSUE TITLE
Add additional arguments not present in python version compared to R version

### ISSUE THREAD

**Issue by nauscj** [business-science/pytimetk#294]
Add additional arguments from R version of pad_by_time()

pad_by_time(
  .data,
  .date_var,
  .by = "auto",
  .pad_value = NA, # Add
  .fill_na_dire[c](https://rdrr.io/r/base/c.html)tion = c("none", "down", "up", "downup", "updown"), #  Add
  .start_date = NULL, # Add
  .end_date = NULL # Add
)

Additionally, a .group_by argument would we useful.

**Comment by mdancho84** [comment]
The group_by is already available. Just group the data frame before you use `.pad_by_time()`.

Example of Grouped Functionality:
```{python}
# Pad by Group: Pad each group with missing dates
padded_df = (
    df
        .groupby('symbol')
        .pad_by_time(
            date_column = 'date',
            freq        = 'D'
        )
)
```

We don't have automatic frequency detection available. 

For the fill NA - I think I'd prefer to let the user fill NA values with pandas.

**Comment by nauscj** [comment]
Sounds good Matt, thank you.
