### ISSUE TITLE
.augment_lags() and .augment_leads()  value_column only accepts numeric dtype

### ISSUE THREAD

**Issue by nauscj** [business-science/pytimetk#295]
Allow .augments_lags() and .augments_leads() to accept non-numeric dtypes. It is often useful get the lag of a string or even the date_column itself. For example it is often useful to take the time difference between an event and the last time the event occurred in an irregular time series.

import pandas as pd
import pytimetk as tk

df = tk.load_dataset('m4_daily', parse_dates=['date'])

df['string_value'] = df['value'].astype(str)

df.augment_lags(
            date_column='date',
            value_column='string_value',
            lags=(1, 7),
            engine='pandas'
        )

# TypeError: `value_column` (string_value) is not a numeric dtype.

# Lag of string column
df['string_value_shifted'] = (
    df.groupby(['id'])['string_value'].shift(1)
)

# Lag of date column
df['date_shifted'] = (
    df.groupby(['id'])['date'].shift(1)
)

df

**Comment by mdancho84** [comment]
Ok, this is incorporated. The function still requires a date_column to be identified as that's pretty standard with pytimetk. But it now accepts non-numeric dtype. 

You can update with this until the next version hits Pypi:

``` bash
pip install git+https://github.com/business-science/pytimetk.git
```

## Lags

![image](https://github.com/user-attachments/assets/0397bb08-91fc-42c6-a517-e23ef538e1e2)

## Leads

![image](https://github.com/user-attachments/assets/1df50b4f-c413-4367-a88e-a8afe4252a1b)

**Comment by nauscj** [comment]
Thanks Matt!
