### ISSUE TITLE
TypeError: plot_timeseries() got an unexpected keyword argument 'plotly_dropdown'

### ISSUE THREAD

**Issue by joaopcnogueira** [business-science/pytimetk#302]
It seems that the pytimetk now does not support dropdown plots with plotly anymore. Although in the [documentation page](https://business-science.github.io/pytimetk/reference/plot_timeseries.html) of the function there is a reference, it does not work. By looking at the `plot_timeseries.py` module installed, in fact there isn't a reference to this argument `plotly_dropdown`.

Is that true or maybe it could be fixed to include the `plot_timeseries.py` module with the `plotly_dropdown` argument? Also, I couldn't find anything related to this deprecation in the releases page, but was able to find that in the current github repository there is a reference to the argument, so maybe this could be that the package hosted in PyPI is different from the one hosted on github.

**Comment by mdancho84** [comment]
It's a developmental feature. I haven't released to pypi yet. Make sure to install the dev version.

**Comment by joaopcnogueira** [comment]
Nice! I have installed the dev version and it's working fine. Thank you!
