### ISSUE TITLE
Applied Tutorial: Demand Forecasting (showcase `tk.augment_timeseries_signature`)

### ISSUE THREAD

**Issue by mdancho84** [business-science/pytimetk#48]
- [ ] Dataset: Please use walmart_sales dataset since its demand forecasting

- [ ] Future Frame: Make use of the future frame function to create future dates by ID. This will allow us to show the future forecast.

- [ ] Plotting: where possible use plot timeseries.

**Comment by GTimothee** [comment]
I can do this if you want, it would be my pleasure

**Comment by GTimothee** [comment]
Hi, I tried to give it a shot. Please tell me what you think about it and I would be please to improve my solution: 
#75

**Comment by mdancho84** [comment]
Thanks. Let me give it a look.
