### ISSUE TITLE
Plot_timeseries - bug

### ISSUE THREAD

**Issue by tackes** [business-science/pytimetk#55]
Creating ticket for a known bugs in plot_timeseries.

Removed tests on these until bugs are fixed.
- [ ] BUG in plotly with "v" direction

**Comment by mdancho84** [comment]
I think the color column should be fixed. I rewrote that code and it looked like it was working. 

Did you see something different with `plot_timeseries`?

**Comment by tackes** [comment]
I get an 'unexpected argument group_names ' error.


import pandas as pd
import numpy as np
data = pd.DataFrame({
    'date': pd.date_range(start='1/1/2020', periods=5, freq='D'),
    'value': np.random.randn(5),
    'id': ['A', 'A', 'B', 'B', 'B']
})

data.plot_timeseries(date_column="date", value_column="value", color_column="id", group_names='id',engine="plotly")

**Comment by mdancho84** [comment]
You might be using an old version of `plot_timeseries`. Try git pull to get the latest. Make sure your forked repo is up to date. I'm constantly updating.

**Comment by mdancho84** [comment]
group_names isn't a variable

**Comment by mdancho84** [comment]
Got to do `.groupby()`

**Comment by tackes** [comment]
My bad, read documentation wrong.

I also tested the facet_dir = 'v' and it seems to be working.  
Possibly just had outdated version.  

I will close the issue.

**Comment by mdancho84** [comment]
`facet_dir = "v"`: It works for `engine = "plotnine"`. Doesn't for `engine = "plotly"`.
