### ISSUE TITLE
Quick roadmap corrections

### ISSUE THREAD

**Issue by JustinKurland** [business-science/pytimetk#9]
Priority 3 - Augment Operations **-> change to** `Priority 4 - Augment Operations`
Note - These functions should overwrite columns that are named the same in the input data frame.

 tk_augment_timeseries_signature() - tk_get_timeseries_signature()
 tk_augment_lags() / tk_agument_leads() - Will need lag_vec() , lead_vec()
 tk_augment_slidify() - May need slidify_vec()
 **add** `tk_augment_holiday_signature()` **and check it once merge request is completed**

**Comment by mdancho84** [comment]
Fixed. I've also added `tk.augment_fourier()`. We should have that one too.
