### ISSUE TITLE
summarize_by_time - corr

### ISSUE THREAD

**Issue by JustinKurland** [business-science/pytimetk#91]
`corr` does not appear to be a valid `agg_function`

For example:
```
df \
    .groupby("category_2") \
    .summarize_by_time(
        date_column='order_date', 
        value_column= ['total_price'],
        freq = "MS",
        agg_func = ['corr']
    )
```
    
Will generate the error:
`AttributeError: 'corr' is not a valid function for 'DatetimeIndexResamplerGroupby' object`

I think simply modifying the docstring here:

```
        - "sum": Sum of values
        - "mean": Mean of values
        - "median": Median of values
        - "min": Minimum of values
        - "max": Maximum of values
        - "std": Standard deviation of values
        - "var": Variance of values
        - "first": First value in group
        - "last": Last value in group
        - "count": Count of values
        - "nunique": Number of unique values
        - "corr": Correlation between values <- Just remove
```
is the simplest solution. I am not entirely sure what the intended use for `corr` here was anyway, was it for comparing to features/covariates or was it meant to compare from t1 to t2 to t3 ... 

Regardless should just tweak the docstring for now. 

In addition, the function as currently written includes a 'kind' parameter, this defaults to 'timestamp', but that it will work for 'period' is also not specified. This should be included in the docstring.

**Comment by mdancho84** [comment]
Thanks for pointing this out. I'm wondering if there should be a functionality to return corr or summarizations that account for multiple columns. This is the same thing we are running into with augment_rolling.
